version: '3.8'

networks:
  blockchain:
    name: blockchain
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

services:
  geth:
    image: ethereum/client-go:v1.14.11
    container_name: geth
    restart: always
    user: "1000:1000" # Run as non-root user
    security_opt:
      - no-new-privileges:true
    command: |
      --datadir=/opt/data/geth
      --state.scheme=path
      --db.engine=leveldb
      --syncmode=snap
      --cache=2048
      --cache.trie=50
      --ws
      --ws.origins=*
      --ws.addr=0.0.0.0
      --ws.api=admin,debug,web3,eth,txpool,personal,miner,net
      --http
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.api=admin,debug,web3,eth,txpool,personal,miner,net
      --http.vhosts=*
      --maxpeers=100
      --nousb
      --port=30304
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=9090
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
      --authrpc.jwtsecret=/opt/data/jwtsecret/jwtsecret
    ports:
      - "8545:8545" # HTTP
      - "8546:8546" # WebSocket
      - "8551:8551" # Auth RPC
      - "30304:30304/tcp" # Discovery TCP
      - "30304:30304/udp" # Discovery UDP
      - "9090:9090" # Metrics
    volumes:
      - /opt/data/geth:/opt/data/geth # Persistent data
      - /opt/data/jwtsecret:/opt/data/jwtsecret # JWT secret
    networks:
      - blockchain
    deploy:
      resources:
        limits:
          memory: 23g
        reservations:
          memory: 20g
    restart: "no"
